# Generated by Django 4.1.7 on 2023-09-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_user_followers_post_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
